# fly.toml app configuration file generated for react-pokedex-2023-back on 2025-11-28T04:14:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'react-pokedex-2023-back'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
